[package]
name = "non-fungible-token"
version = "1.1.0"
authors = ["Luciferius <twitter.cryptosketches@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
near-sdk = "4.0.0-pre.8"
near-contract-standards = "4.0.0-pre.8"
